name: clinic_mobile_app
description: A Smart Clinic Management System built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  provider: ^6.0.5
  http: ^1.1.0
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  fl_chart: ^0.63.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.4.0
  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
